// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UndoMessageBean.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UndoMessageBean.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UndoMessageBeanRoot

@implementation UndoMessageBeanRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - UndoMessageBeanRoot_FileDescriptor

static GPBFileDescriptor *UndoMessageBeanRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"proto"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - UndoMessage

@implementation UndoMessage

@dynamic hasMsgId, msgId;
@dynamic hasType, type;
@dynamic hasTid, tid;
@dynamic hasChatType, chatType;
@dynamic hasUuid, uuid;
@dynamic hasIsRead, isRead;
@dynamic hasMemberId, memberId;
@dynamic hasCreateTime, createTime;
@dynamic hasName, name;

typedef struct UndoMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  int32_t chatType;
  NSString *msgId;
  NSString *uuid;
  NSString *name;
  int64_t tid;
  int64_t memberId;
  int64_t createTime;
} UndoMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgId",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_MsgId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, msgId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_Type,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, type),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tid",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_Tid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, tid),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "chatType",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_ChatType,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, chatType),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "uuid",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_Uuid,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, uuid),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isRead",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_IsRead,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "memberId",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_MemberId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, memberId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "createTime",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_CreateTime,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, createTime),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = UndoMessage_FieldNumber_Name,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(UndoMessage__storage_, name),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UndoMessage class]
                                     rootClass:[UndoMessageBeanRoot class]
                                          file:UndoMessageBeanRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UndoMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\005\000\004\010\000\006\006\000\007\010\000\010\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
