// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UndoMessageBean.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UndoMessageBeanRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UndoMessageBeanRoot : GPBRootObject
@end

#pragma mark - UndoMessage

typedef GPB_ENUM(UndoMessage_FieldNumber) {
  UndoMessage_FieldNumber_MsgId = 1,
  UndoMessage_FieldNumber_Type = 2,
  UndoMessage_FieldNumber_Tid = 3,
  UndoMessage_FieldNumber_ChatType = 4,
  UndoMessage_FieldNumber_Uuid = 5,
  UndoMessage_FieldNumber_IsRead = 6,
  UndoMessage_FieldNumber_MemberId = 7,
  UndoMessage_FieldNumber_CreateTime = 8,
  UndoMessage_FieldNumber_Name = 9,
};

/**
 * 撤销消息
 **/
@interface UndoMessage : GPBMessage

/** 消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

/** 撤销或删除 (1删除，2撤销) */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
/** 接收者id (個人,群組,班級) */
@property(nonatomic, readwrite) int64_t tid;

@property(nonatomic, readwrite) BOOL hasTid;
/** 班级，群组，个人 */
@property(nonatomic, readwrite) int32_t chatType;

@property(nonatomic, readwrite) BOOL hasChatType;
/** 系統消息uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

/** 是否已读 */
@property(nonatomic, readwrite) BOOL isRead;

@property(nonatomic, readwrite) BOOL hasIsRead;
/** 接收人id */
@property(nonatomic, readwrite) int64_t memberId;

@property(nonatomic, readwrite) BOOL hasMemberId;
/** 消息创建时间 */
@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
/** 发送人名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
