// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustLoginBean.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CustLoginBeanRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CustLoginBeanRoot : GPBRootObject
@end

#pragma mark - CustLogin

typedef GPB_ENUM(CustLogin_FieldNumber) {
  CustLogin_FieldNumber_Id_p = 1,
  CustLogin_FieldNumber_Devinfos = 2,
  CustLogin_FieldNumber_UserName = 3,
  CustLogin_FieldNumber_Pwd = 4,
  CustLogin_FieldNumber_Platform = 5,
  CustLogin_FieldNumber_Version = 6,
};

/**
 * 登录
 **/
@interface CustLogin : GPBMessage

/** id */
@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
/** 设备号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *devinfos;
/** Test to see if @c devinfos has been set. */
@property(nonatomic, readwrite) BOOL hasDevinfos;

/** 用户名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

/** 密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pwd;
/** Test to see if @c pwd has been set. */
@property(nonatomic, readwrite) BOOL hasPwd;

/** 平台(ios or android) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;
/** Test to see if @c platform has been set. */
@property(nonatomic, readwrite) BOOL hasPlatform;

/** 版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
