// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustLoginBean.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "CustLoginBean.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CustLoginBeanRoot

@implementation CustLoginBeanRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - CustLoginBeanRoot_FileDescriptor

static GPBFileDescriptor *CustLoginBeanRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"proto"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - CustLogin

@implementation CustLogin

@dynamic hasId_p, id_p;
@dynamic hasDevinfos, devinfos;
@dynamic hasUserName, userName;
@dynamic hasPwd, pwd;
@dynamic hasPlatform, platform;
@dynamic hasVersion, version;

typedef struct CustLogin__storage_ {
  uint32_t _has_storage_[1];
  NSString *devinfos;
  NSString *userName;
  NSString *pwd;
  NSString *platform;
  NSString *version;
  int64_t id_p;
} CustLogin__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CustLogin__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "devinfos",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_Devinfos,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CustLogin__storage_, devinfos),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userName",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_UserName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CustLogin__storage_, userName),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pwd",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_Pwd,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CustLogin__storage_, pwd),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "platform",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_Platform,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CustLogin__storage_, platform),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = CustLogin_FieldNumber_Version,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CustLogin__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CustLogin class]
                                     rootClass:[CustLoginBeanRoot class]
                                          file:CustLoginBeanRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CustLogin__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
